const actions = {
    GET_USERS: "GET_USERS",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",
    GET_RECENT_USERS: "GET_RECENT_USERS",
    GET_RECENT_USERS_SUCCESS:"GET_RECENT_USERS_SUCCESS"
};

export default actions;